-- Extend roi_leads with fields required by ROI form (idempotent)
ALTER TABLE public.roi_leads ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE public.roi_leads ADD COLUMN IF NOT EXISTS pain_points TEXT[];
ALTER TABLE public.roi_leads ADD COLUMN IF NOT EXISTS spend_range TEXT;
ALTER TABLE public.roi_leads ADD COLUMN IF NOT EXISTS use_case_preset TEXT;
ALTER TABLE public.roi_leads ADD COLUMN IF NOT EXISTS offload_percent NUMERIC;
ALTER TABLE public.roi_leads ADD COLUMN IF NOT EXISTS prompt_reduction_percent NUMERIC;
ALTER TABLE public.roi_leads ADD COLUMN IF NOT EXISTS caching_hit_rate_percent NUMERIC;
ALTER TABLE public.roi_leads ADD COLUMN IF NOT EXISTS batching_efficiency_percent NUMERIC;
ALTER TABLE public.roi_leads ADD COLUMN IF NOT EXISTS hosted_rate_per_k NUMERIC;
ALTER TABLE public.roi_leads ADD COLUMN IF NOT EXISTS projected_new_monthly_cost NUMERIC;
ALTER TABLE public.roi_leads ADD COLUMN IF NOT EXISTS payback_days INTEGER;
ALTER TABLE public.roi_leads ADD COLUMN IF NOT EXISTS baseline_monthly_tokens NUMERIC;
ALTER TABLE public.roi_leads ADD COLUMN IF NOT EXISTS offloaded_tokens NUMERIC;
ALTER TABLE public.roi_leads ADD COLUMN IF NOT EXISTS hosted_token_cost NUMERIC;
ALTER TABLE public.roi_leads ADD COLUMN IF NOT EXISTS remaining_api_cost NUMERIC;
ALTER TABLE public.roi_leads ADD COLUMN IF NOT EXISTS new_monthly_cost NUMERIC;
ALTER TABLE public.roi_leads ADD COLUMN IF NOT EXISTS detailed_report TEXT;
